#!/bin/bash

set -x 

source $HOME/.bashrc

echo "CHROMIUM_FLAGS='--no-sandbox --disable-gpu --user-data-dir'" > $HOME/.chromium-browser.init

vncserver -kill $DISPLAY || rm -rfv /tmp/.X*-lock /tmp/.X11-unix
vncserver :1 -geometry $VNC_RESOLUTION -depth $VNC_COL_DEPTH && tail -F $HOME/.vnc/*$DISPLAY.log
